### ISSUE TITLE
undefined reference to `XEM::ModelOutput::getModel() const

### ISSUE THREAD

**Issue by jschueller** [mixmod/mixmod#22]
class ModelOutput has  a `Model * getModel() const;` method declared but its not defined:
https://github.com/mixmod/mixmod/blob/master/mixmodLib/SRC/mixmod/Kernel/IO/ModelOutput.h#L91

how can I get the Model after a clustering step is done ? my code looks like this:

```
// Prepare Mixmod for clustering
  XEM::ClusteringInput * clusteringInput(new XEM::ClusteringInput(nbCluster, dataDescription));
  XEM::ModelType modelType(XEM::StringToModelName(covarianceModel_));
  clusteringInput->setModelType(&modelType, 0);
  clusteringInput->finalize();

  // Do the computation
  XEM::ClusteringMain clusteringMain(clusteringInput);
  clusteringMain.run();

  // Extract the results
  XEM::ClusteringOutput * clusteringOutput(clusteringMain.getOutput());

  XEM::ClusteringModelOutput * clusteringModelOutput(clusteringOutput->getClusteringModelOutput(0));
```

the goal is to get logLikelihood & entropy results, I see there is a LikelihoodOutput class but I need the model

**Comment by Quentin62** [comment]
Honestly, I don't know the architecture of mixmod, the different classes...
I used the R package and I was asked to maintain it to keep it on CRAN.

There are some c++ examples here:
https://github.com/mixmod/mixmod/tree/master/mixmodLib/EXAMPLES

In the old archived repo, I found some doc that I recompile, it contains a section dedicated to using the c++ library

[userguide.pdf](https://github.com/mixmod/mixmod/files/13438824/userguide.pdf)

**Comment by jschueller** [comment]
ok, thanks anyways
